config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :exams
  resources :high_scores
  devise_for :users, controllers: { registrations: "users/registrations", sessions: 'users/sessions', passwords: "users/passwords", omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'

  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user, optional: :true
  has_many :pictures, as: :imageable
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i(edit update destroy)

  def create
    @location = current_user.locations.new(permitted_location_params)
    call_method
    if @location.save
      LocationMailer.create_location(@location, current_user).deliver_now
      redirect_to locations_path, notice: 'Location was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @location.update(permitted_location_params)
      flash[:notice] = 'Location was successfully updated.'
      redirect_to locations_path
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_url, notice: 'Location was successfully destroyed.'
  end

  def new
    @location = Location.new
  end

  def index
    @locations = Location.all
  end

  def call_method
    puts "fssdfdsgd"
  end

  private

  def set_location
    @location = Location.find_by(params[:id])
  end

  def permitted_location_params
    params.require(:location).permit(:id, :loc_name, :city, :state, :zipcode)
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= simple_form_for(@location, html: { class: '' }) do |f| %>
  <% if @location.errors.any? %>
    <div id='error_explanation'>
      <ul>
        <% @location.errors.each do |attri, msg| %>
          <li>
            <%= attri %> <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs location_frm">

    <%= f.label :loc_name, '*Location Name' %>
    <%= f.input :loc_name, label: false %>

    <%= f.label :city, '*City' %>
    <%= f.input :city, label: false %>

    <%= f.label :state, 'State' %>
    <%= f.input :state, label: false %>

    <%= f.label :zipcode %>
    <%= f.input :zipcode, label: false %>

      <%#= f.label :logo, 'Upload Logo'%>
      <%#= f.file_field :logo, label: false %>
    <%# end %>

    <div class="form-actions">
      <% if @location.persisted? %>
        <button name="button" type="submit" class="send_invite_btn">Update Location</button>
      <% else %>
        <button name="button" type="submit" class="send_invite_btn">Create Location</button>
      <% end %>
    </div>
  </div>
<% end %>

app/views/locations/create.html.erb
<h1>Locations#create</h1>
<p>Find me in app/views/locations/create.html.erb</p>

app/views/locations/destroy.html.erb
<h1>Locations#destroy</h1>
<p>Find me in app/views/locations/destroy.html.erb</p>

app/views/locations/edit.html.erb
<div class="form_heading dashboard_form">
  <h1>Edit Location</h1>
  <div class="frm_setting_col">
    <div class="col-md-4 col-md-offset-4">
      <%= render 'form', location: @location %>
      <div class="cancel_col">
        <%= link_to 'Cancel', locations_path %>
      </div>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<div class='form_heading dashboard_form'>
  <h1>Manage Locations</h1>
  <div class='frm_setting'>
    <div class="user_table">
      <table class='table'>
        <thead>
          <tr>
            <th>Location Name</th>
            <th>State</th>
            <th>City</th>
            <th>ZipCode</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @locations.each do |location| %>
            <tr>
              <td><%= location.loc_name %></td>
              <td><%= location.state %></td>
              <td><%= location.city %></td>
              <td><%= location.zipcode %></td>
              <td><%= link_to 'Edit', edit_location_path(location) %></td>
              <td><%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<div class='form_heading dashboard_form'>
  <h1>Add New Location</h1>
  <div class="frm_setting_col">
    <div class="col-md-4 col-md-offset-4">
      <%= render 'form', location: @location %>
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.erb</p>

app/views/locations/update.html.erb
<h1>Locations#update</h1>
<p>Find me in app/views/locations/update.html.erb</p>