config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :exams
  resources :high_scores
  devise_for :users, controllers: { registrations: "users/registrations", sessions: 'users/sessions', passwords: "users/passwords", omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'

  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <%= link_to 'Home', root_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Location', locations_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Exam', exams_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Logout', destroy_user_session_path, class: "nav-link" %>
    </li>
  </ul>
</nav>

<!-- <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">Active</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" href="#">Disabled</a>
    </li>
  </ul>
</nav> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
  <%= render 'toastr_rails/flash'%>
</html>